# _config.yml
title: "Marcelle Larissa Tankui Tchouamouo - Développeuse FullStack"
description: "Portfolio professionnel - Développeuse FullStack spécialisée FinTech et systèmes distribués"
baseurl: ""
url: "https://MarcelleT01.github.io"

# Thème Cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Photo de profil
avatar: "images/05fedfd-8eae-4778-9870-1c2dff8bd6f7.jpeg"

# Auteur
author: "Marcelle Larissa Tankui Tchouamouo"
email: "mtchouamouo@gmail.com"

# Social
github_username: MarcelleT01
linkedin_username: marcelle-tchouamouo

lang: "fr"
